CREATE OR REPLACE PROCEDURE CN.pr_Inserta_Nuevos_Registros
(p_datos IN VARCHAR2, P_ESTADO OUT VARCHAR)
IS
V_REGISTROS     cn.Leer_Cadena.T_ARRAY_STRING;
V_CAMPOS        cn.Leer_Cadena.T_ARRAY_STRING;

BEGIN
     V_REGISTROS := CN.Leer_Cadena.SPLIT(P_DATOS,'¬');
     
     FOR I in 1 .. V_REGISTROS.COUNT LOOP 
		
        V_CAMPOS := CN.Leer_cadena.SPLIT(V_REGISTROS(I),'|');
        
        INSERT INTO CN.DETALLE_CN(ANO_PROG,CENTRO_COSTO, TIPO_ITEM, CODIGO_ITEM,UNIDAD_MEDIDA,PRECIO_UNIT, CANT_TOTAL) 
        VALUES(TO_NUMBER(V_CAMPOS(1)), V_CAMPOS(2), V_CAMPOS (3), V_CAMPOS (4), TO_NUMBER(V_CAMPOS(5)), TO_NUMBER(V_CAMPOS(6)), TO_NUMBER (V_CAMPOS (7)) );
                    
    END LOOP;    
    COMMIT;
    P_ESTADO := 'OK';
EXCEPTION
    WHEN OTHERS THEN
        P_ESTADO := SQLERRM;
        ROLLBACK;
END;

/* EJECUTAR PROCEDIMIENTO ALMACENADO*/

DECLARE 
V_ESTADO VARCHAR2(300);
BEGIN
    CN.PR_INSERTA_NUEVOS_REGISTROS ('2019|01.12.05|B|497000029999|112|750|1¬2019|1.7.3.2|B|497000029999|112|250|1¬2019|1.1.2|B|497000029999|112|50|1', V_ESTADO);
    DBMS_OUTPUT.PUT_LINE( V_ESTADO );
END;


SELECT * FROM CN.DETALLE_CN
WHERE CODIGO_ITEM= '497000029999';