/**********CREAR SECUENCIAS************/
CREATE SEQUENCE RESERVAS.SEQ_ID_MARCA INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE RESERVAS.SEQ_ID_TIPO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE RESERVAS.SEQ_ID_TIPODOCUMENTO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE RESERVAS.SEQ_ID_COLOR INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE RESERVAS.SEQ_ID_AUTO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE RESERVAS.SEQ_ID_RESERVA INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE RESERVAS.SEQ_ID_RESERVADIA INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE RESERVAS.SEQ_ID_DIAS INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE RESERVAS.SEQ_ID_CLIENTE INCREMENT BY 1 START WITH 1;


/****************INSERTAR MARCA*****************/
INSERT INTO RESERVAS.PRM_MARCA ( N_ID_MARCA, C_NOM_MARCA, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_MARCA.nextVal, 'RENAULT', 0, SYSDATE, 'USU001' );
INSERT INTO RESERVAS.PRM_MARCA ( N_ID_MARCA, C_NOM_MARCA, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_MARCA.nextVal, 'TOYOTA', 0, SYSDATE, 'USU001' );
INSERT INTO RESERVAS.PRM_MARCA ( N_ID_MARCA, C_NOM_MARCA, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_MARCA.nextVal, 'KIA', 0, SYSDATE, 'USU001' );
INSERT INTO RESERVAS.PRM_MARCA ( N_ID_MARCA, C_NOM_MARCA, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_MARCA.nextVal, 'NISSAN', 0, SYSDATE, 'USU001' );


/****************INSERTAR COLOR*****************/
INSERT INTO RESERVAS.PRM_COLOR ( N_ID_COLOR, c_nom_color, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_COLOR.nextVal, 'BLANCO', 0, SYSDATE, 'USU001' );
INSERT INTO RESERVAS.PRM_COLOR ( N_ID_COLOR, c_nom_color, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_COLOR.nextVal, 'NEGRO', 0, SYSDATE, 'USU001' );
INSERT INTO RESERVAS.PRM_COLOR ( N_ID_COLOR, c_nom_color, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_COLOR.nextVal, 'AZUL', 0, SYSDATE, 'USU001' );
INSERT INTO RESERVAS.PRM_COLOR ( N_ID_COLOR, c_nom_color, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_COLOR.nextVal, 'ROJO', 0, SYSDATE, 'USU001' );


/****************INSERTAR TIPO*****************/
INSERT INTO RESERVAS.PRM_TIPO ( N_ID_TIPO, C_NOM_TIPO, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_TIPO.nextVal, 'BAJO', 0, SYSDATE, 'USU001' );
INSERT INTO RESERVAS.PRM_TIPO ( N_ID_TIPO, C_NOM_TIPO, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_TIPO.nextVal, 'MEDIO', 0, SYSDATE, 'USU001' );
INSERT INTO RESERVAS.PRM_TIPO ( N_ID_TIPO, C_NOM_TIPO, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_TIPO.nextVal, 'ALTO', 0, SYSDATE, 'USU001' );


/****************INSERTAR TIPO DOCUMENTO*****************/
INSERT INTO RESERVAS.PRM_TIPODOCUMENTO ( N_ID_TIPODOCUMENTO, C_NOM_TIPODOCUMENTO, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_TIPODOCUMENTO.nextVal, 'D.N.I.', 0, SYSDATE, 'USU001' );
INSERT INTO RESERVAS.PRM_TIPODOCUMENTO ( N_ID_TIPODOCUMENTO, C_NOM_TIPODOCUMENTO, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_TIPODOCUMENTO.nextVal, 'PASAPORTE', 0, SYSDATE, 'USU001' );
INSERT INTO RESERVAS.PRM_TIPODOCUMENTO ( N_ID_TIPODOCUMENTO, C_NOM_TIPODOCUMENTO, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_TIPODOCUMENTO.nextVal, 'C.E.', 0, SYSDATE, 'USU001' );


/****************INSERTAR DIAS*****************/
--SET SERVEROUTPUT ON;
BEGIN
  FOR I IN 0 .. 365
  LOOP
    INSERT INTO RESERVAS.PRM_DIAS ( N_ID_DIAS, D_DES_DIA, N_IND_LABORABLE, C_DES_NOLABORABLE, D_FEC_CREA, C_COD_USUCREA)
    SELECT RESERVAS.SEQ_ID_DIAS.nextVal, TO_DATE('01-01-2018','DD-MM-YYYY') + I,
    CASE WHEN to_char(TO_DATE('01-01-2018','DD-MM-YYYY') + I, 'DAY', 'NLS_DATE_LANGUAGE=SPANISH') LIKE 'S%' THEN 0
    WHEN to_char(TO_DATE('01-01-2018','DD-MM-YYYY') + I, 'DAY', 'NLS_DATE_LANGUAGE=SPANISH') LIKE 'D%' THEN 0 ELSE 1 END, 
    NULL, SYSDATE, 'USU001' 
    FROM DUAL;
  END LOOP;
END;


/****************INSERTAR CLIENTE*****************/
INSERT INTO RESERVAS.MSE_CLIENTE ( N_ID_CLIENTE, C_DES_NOMBRES, C_DES_APPATERNO, C_DES_APMATERNO,
N_ID_TIPODOCUMENTO, C_DES_DOCUMENTO, D_FEC_NACIMIENTO, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_CLIENTE.nextVal, 'MARIA', 'GRADOS', 'ASCENCIO',
1, '01234567', TO_DATE('01-01-1955','DD-MM-YYYY'), 0, SYSDATE, 'USU001' );
INSERT INTO RESERVAS.MSE_CLIENTE ( N_ID_CLIENTE, C_DES_NOMBRES, C_DES_APPATERNO, C_DES_APMATERNO,
N_ID_TIPODOCUMENTO, C_DES_DOCUMENTO, D_FEC_NACIMIENTO, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_CLIENTE.nextVal, 'BENJAMIN', 'GRADOS', 'ASCENCIO',
1, '23456789', TO_DATE('01-01-1960','DD-MM-YYYY'), 0, SYSDATE, 'USU001' );

/****************INSERTAR AUTO*****************/
INSERT INTO RESERVAS.MSE_AUTO ( N_ID_AUTO, N_ID_MARCA, N_ID_TIPO, N_ID_COLOR, N_NUM_ASIENTOS, 
N_MON_PRECIODIA, C_DES_PLACA, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_AUTO.nextVal, 1,1,1,4,
100,'ABC-123', 0, SYSDATE, 'USU001' );
INSERT INTO RESERVAS.MSE_AUTO ( N_ID_AUTO, N_ID_MARCA, N_ID_TIPO, N_ID_COLOR, N_NUM_ASIENTOS, 
N_MON_PRECIODIA, C_DES_PLACA, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_AUTO.nextVal, 1,2,1,4,
120,'ABC-123', 0, SYSDATE, 'USU001' );
INSERT INTO RESERVAS.MSE_AUTO ( N_ID_AUTO, N_ID_MARCA, N_ID_TIPO, N_ID_COLOR, N_NUM_ASIENTOS, 
N_MON_PRECIODIA, C_DES_PLACA, N_IND_ESTADO, D_FEC_CREA, C_COD_USUCREA)
VALUES (RESERVAS.SEQ_ID_AUTO.nextVal, 1,3,1,4,
150,'ABC-123', 0, SYSDATE, 'USU001' );