BEGIN
	RESERVAS.PKG_RESERVA_CRUD.INS_MARCA ('SUZUKI', 'USU002');
END;

DECLARE
  RESUL VARCHAR2(1000);
BEGIN
	RESERVAS.PR_INS_RESERVA_SIMPLE (1,1,'DETALLE', SYSDATE, SYSDATE+1, 'USU003', RESUL);
END;
