/**********SELECT A LA TABLA*************/
SELECT * FROM SCOTT.EMP;

/**********CREANDO CAMPO A LA TABLA*************/
ALTER TABLE SCOTT.EMP
ADD CNT_UPDATE NUMBER(5) DEFAULT(0);

/**********CREAR TRIGGER A LA TABLA*************/
CREATE OR REPLACE TRIGGER scott.TR_UPD_EMP
BEFORE UPDATE ON SCOTT.EMP 
FOR EACH ROW
BEGIN
	IF UPDATING ('SAL') THEN 
		UPDATE SCOTT.EMP
		SET CNT_UPDATE = CNT_UPDATE + 1
		WHERE EMPNO = :NEW.EMPNO;
	END IF;
END TR_UPD_EMP;
	
/**********ACTUALIZANDO REGISTRO DE LA TABLA*************/
UPDATE SCOTT.EMP
SET ENAME = 'PEDRO'
WHERE EMPNO =7777;

/**********VALIDANDO: SELECT A LA TABLA*************/
SELECT * FROM SCOTT.EMP
WHERE EMPNO =7777;
