/**********CREANDO LA TABLA*************/
CREATE TABLE scott.SAL_HISTORY(
  EMPNO NUMBER(4) NOT NULL,
  SALOLD NUMBER(7,2) NULL,
  SALNEW NUMBER(7,2) NULL,
  STARTDATE DATE NOT NULL,
  SETUSER VARCHAR2(30) NOT NULL
  );

/**********CREAR TRIGGER A LA TABLA*************/
CREATE OR REPLACE TRIGGER TR_UPDATEEMPSAL
AFTER INSERT OR UPDATE ON EMP
FOR EACH ROW
BEGIN
   IF inserting OR updating('SAL') THEN
     INSERT INTO SAL_HISTORY (EMPNO, SALOLD, SALNEW, STARTDATE, SETUSER)
     VALUES(:NEW.EMPNO, :OLD.SAL, :NEW.SAL, SYSDATE,USER);
   END IF;
END TR_UPDATEEMPSAL;


INSERT INTO scott.emp(empno, ename, sal)
VALUES(7,'demo 7',300);

COMMIT;

	
/**********ACTUALIZANDO REGISTRO DE LA TABLA*************/
UPDATE SCOTT.EMP
SET SAL = 1500
WHERE EMPNO =7777;

/**********VALIDANDO: SELECT A LA TABLA*************/
SELECT * FROM SCOTT.EMP
WHERE EMPNO =7777;

SELECT * FROM SCOTT.SAL_HISTORY;