/**********CREANDO LA TABLA*************/
CREATE OR REPLACE VIEW SCOTT.V_EMPLEADOS AS
SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME
FROM SCOTT.EMP E INNER JOIN SCOTT.DEPT D
ON E.DEPTNO = D.DEPTNO;

/**********CREAR TRIGGER A LA TABLA*************/
CREATE OR REPLACE TRIGGER scott.TR_VISTA
INSTEAD OF INSERT OR DELETE ON SCOTT.V_EMPLEADOS
FOR EACH ROW
DECLARE CUENTA NUMBER;
BEGIN
      IF INSERTING THEN
        SELECT COUNT(*) INTO CUENTA FROM SCOTT.DEPT WHERE DEPTNO = :NEW.DEPTNO;
        IF CUENTA = 0 THEN
          INSERT INTO SCOTT.DEPT(DEPTNO, DNAME)
          VALUES(:NEW.DEPTNO, :NEW.DNAME);
        END IF;
        
        SELECT COUNT(*) INTO CUENTA FROM SCOTT.EMP WHERE EMPNO = :NEW.EMPNO;
        
        IF CUENTA = 0 THEN 
          INSERT INTO SCOTT.EMP(EMPNO, ENAME, DEPTNO)
          VALUES(:NEW.EMPNO, :NEW.ENAME, :NEW.DEPTNO);
        END IF;
      ELSIF DELETING THEN
        DELETE FROM EMP WHERE EMPNO = :OLD.EMPNO;
      END IF;
      
END TR_VISTA;
	
        
INSERT INTO SCOTT.V_EMPLEADOS
VALUES(10, 'PEDRO', 1, 'DEPT01');

UPDATE scott.V_EMPLEADOS
SET ENAME = 'abc'
WHERE EMPNO = 10;

UPDATE scott.V_EMPLEADOS
SET DNAME = 'abc'
WHERE deptno = 1;


SELECT * FROM scott.emp ORDER BY 1;
SELECT * FROM scott.DEPT;