
-- =============================================
-- OTROS ELEMENTOS
-- =============================================


-- SEQUENCIAS

CREATE SEQUENCE SCOTT.SQ_DEMO;


SELECT SCOTT.SQ_DEMO.NEXTVAL FROM DUAL;



-- TABLA TEMPORAL

CREATE GLOBAL TEMPORARY TABLE SCOTT.DEPT_PLANILLA(
	DEPTNO   NUMBER(6),
	DNAME    VARCHAR2(20),
	EMPS     NUMBER(6),
	PLANILLA NUMBER(10,2)
)ON COMMIT DELETE ROWS;


INSERT INTO SCOTT.DEPT_PLANILLA 
(DEPTNO, EMPS, PLANILLA)
SELECT DEPTNO, COUNT(1), SUM(SAL)
FROM SCOTT.EMP
GROUP BY DEPTNO;

SELECT * FROM SCOTT.DEPT_PLANILLA;


COMMIT;

SELECT * FROM SCOTT.DEPT_PLANILLA;


INSERT INTO SCOTT.DEPT_PLANILLA 
(DEPTNO, EMPS, PLANILLA)
SELECT DEPTNO, COUNT(1), SUM(SAL)
FROM SCOTT.EMP
GROUP BY DEPTNO;

SELECT * FROM SCOTT.DEPT_PLANILLA;

UPDATE SCOTT.DEPT_PLANILLA A
SET DNAME = (SELECT DNAME FROM SCOTT.DEPT B WHERE A.DEPTNO = B.DEPTNO);


SELECT * FROM SCOTT.DEPT_PLANILLA;


COMMIT;


