

CREATE OR REPLACE FUNCTION SCOTT.fn_operacion
( P_N1 IN NUMBER, P_N2 IN NUMBER, P_OP IN CHAR ) RETURN VARCHAR2
IS

	V_RESULTADO VARCHAR(50);
	
BEGIN
	CASE P_OP
		WHEN '+' THEN 
			V_RESULTADO := TO_CHAR(P_N1 + P_N2);
			
		WHEN '-' THEN
			V_RESULTADO := TO_CHAR(P_N1 - P_N2);
			
		WHEN '*' THEN
			V_RESULTADO := TO_CHAR(P_N1 * P_N2);
			
		WHEN '/' THEN
			V_RESULTADO := TO_CHAR(P_N1 / P_N2);
			
		ELSE
			V_RESULTADO := 'NONE';
			
	END CASE;
	
	RETURN V_RESULTADO;
END;