/*
TAREA 3 
HACER UN PROCEDIMIENTO QUE PERMITA MOSTRAR UN MENSAJE "N" VECES 
UTILIZAR LOOP .. END LOOP
*/

CREATE OR REPLACE PROCEDURE SCOTT.PR_REPETIR
(P_N1 IN VARCHAR2 ,P_N2 IN NUMBER)
AS
CONTADOR INT;
BEGIN
	CONTADOR := 0;
    LOOP
    	IF CONTADOR =P_N2 THEN
    		EXIT;
    	END IF;
 		dbms_output.PUT_LINE('PINTAR : ' || P_N1);
 		CONTADOR := CONTADOR +1;
    END LOOP;
END;


BEGIN
	SCOTT.PR_REPETIR ('HOLA', 5);
END;