CREATE OR REPLACE PROCEDURE SCOTT.PR105(COD EMP.EMPNO%TYPE)
IS
	TYPE REG IS RECORD (
		NOMBRE EMP.ENAME%TYPE,
		SALARIO EMP.SAL%TYPE
	);
	R REG;
BEGIN
	SELECT ENAME, SAL INTO R
	FROM SCOTT.EMP WHERE EMPNO = COD;
	DBMS_OUTPUT.PUT_LINE ('NOMBRE: ' || R.NOMBRE);
	DBMS_OUTPUT.PUT_LINE ('SALARIO: ' || R.SALARIO);
END;



BEGIN
	SCOTT.PR105 (7698);
END;
