CREATE OR REPLACE PROCEDURE SCOTT.PR106(COD DEPT.DEPTNO%TYPE)
IS
	R DEPT%ROWTYPE;
BEGIN

	SELECT * INTO R
	FROM DEPT WHERE DEPTNO = COD;
	
	DBMS_OUTPUT.PUT_LINE ('CODIGO: ' || R.DEPTNO);
	DBMS_OUTPUT.PUT_LINE ('NOMBRE: ' || R.DNAME);
	DBMS_OUTPUT.PUT_LINE ('LOCALIZACIÓN: ' || R.LOC);
	
END;



BEGIN
	SCOTT.PR106 (10);
END;
