
SELECT * FROM VENTAS.CATEGORIA;

SELECT * FROM VENTAS.EMPLEADO; 
	
SELECT * FROM VENTAS.PRODUCTO;

SELECT * FROM VENTAS.TIPO_PAGO;

SELECT * FROM VENTAS.USUARIO;


---- INSERT

INSERT INTO VENTAS.EMPLEADO
VALUES (1005,'CRISTINA','OROSCO','cristina1794.ov@gmail.com','987654321')

SELECT * FROM VENTAS.EMPLEADO 


-- SELECT


SELECT * FROM VENTAS.EMPLEADO;

CREATE OR REPLACE PROCEDURE PR4
( P_IDEMP IN NUMBER, P_NOMBRE OUT VARCHAR2 )
AS
BEGIN
	SELECT NOMBRE || ' ' || APELLIDO INTO P_NOMBRE
	FROM EMPLEADO
	WHERE IDEMP = P_IDEMP;
END;


BEGIN
	VENTAS.PR4 (1001, :p_nombre$VARCHAR2);
END;


-- DELETE


SELECT * FROM VENTAS.PRODUCTO

CREATE OR REPLACE PROCEDURE PR2
( P_IDPROD IN NUMBER) 
IS
BEGIN
	DELETE FROM PRODUCTO WHERE IDPROD=P_IDPROD;
END;


BEGIN
	VENTAS.PR2 (1005);
END;

SELECT * FROM VENTAS.PRODUCTO

ROLLBACK;


-- UPDATE

SELECT * FROM VENTAS.PRODUCTO

CREATE OR REPLACE PROCEDURE PR3
( P_IDPROD IN NUMBER) 
IS
BEGIN
	UPDATE PRODUCTO 
	SET STOCK=STOCK-1  WHERE IDPROD=P_IDPROD;
END;


BEGIN
	VENTAS.PR3 (1001);
END;

SELECT * FROM VENTAS.PRODUCTO

ROLLBACK;



---- PROCESO SIMPLE

SELECT * FROM VENTAS.PRODUCTO


CREATE OR REPLACE PROCEDURE PR1
( P_IDPROD IN NUMBER) 
IS
		TYPE REG IS RECORD (
		CATEGOR PRODUCTO.NOMBRE%TYPE,
		PRECIO_ PRODUCTO.PRECIO%TYPE
		);
		R REG;
BEGIN
	UPDATE PRODUCTO
	SET PRECIO=PRECIO+10 WHERE IDPROD=P_IDPROD;
	SELECT NOMBRE, PRECIO INTO R
		FROM VENTAS.PRODUCTO WHERE IDPROD=P_IDPROD;
	DBMS_OUTPUT.PUT_LINE( 'NOMBRE: ' || R.CATEGOR);
	DBMS_OUTPUT.PUT_LINE( 'PRECIO: ' || R.PRECIO_);
END;


BEGIN
	VENTAS.PR1 (1001);
END;


---- CONSULTA DE RESUMEN DE DATOS

SELECT * FROM VENTAS.PRODUCTO

SELECT idcat, count(*) FROM ventas.PRODUCTO GROUP BY idcat

