-- ================================
-- FUNCION PARA CONSULTAR EL SALARIO DE UN EMPLEADO
-- ================================

CREATE OR REPLACE FUNCTION SCOTT.FN_SAL_EMP
(P_EMPNO NUMBER)
RETURN NUMBER
AS
	V_SAL NUMBER;
BEGIN
	-- Proceso
	SELECT SAL INTO V_SAL
	FROM SCOTT.EMP
	WHERE EMPNO = P_EMPNO;
	-- Valor de retorno
	RETURN V_SAL;
END;


SELECT SCOTT.FN_SAL_EMP (53454) FROM DUAL;