

 CREATE OR REPLACE PROCEDURE EUREKA.PR_SALDO_MONEDA
(P_CUENTA IN CUENTA.CHR_CUENCODIGO%TYPE,P_SALDO OUT CUENTA.DEC_CUENSALDO%TYPE,P_MONEDA OUT MONEDA.VCH_MONEDESCRIPCION%TYPE)

AS
BEGIN
	SELECT DEC_CUENSALDO,VCH_MONEDESCRIPCION INTO P_SALDO,P_MONEDA FROM EUREKA.CUENTA C
	INNER JOIN	MONEDA ON MONEDA.CHR_MONECODIGO = C.CHR_MONECODIGO
	WHERE	CHR_CUENCODIGO = P_CUENTA;
END;

SELECT * FROM CLIENTE

BEGIN
	EUREKA.PR_SALDO_MONEDA ('00200002', :p_saldo$NUMBER, :p_moneda$VARCHAR2);
END;
