

-- ================================
-- DESARROLLAR UN PROCEDIMIENTO QUE RETORNE DE UNA CUENTA SU SALDO Y EL NOMBRE DE LA MONEDA
-- ================================

CREATE OR REPLACE PROCEDURE EUREKA.PR_CUENTA_MONEDA
(P_NUCUENTA IN CUENTA.CHR_CUENCODIGO%TYPE, 
P_SAL OUT CUENTA.DEC_CUENSALDO%TYPE, 
P_MONEDA OUT MONEDA.VCH_MONEDESCRIPCION%TYPE)
AS

BEGIN

	SELECT C.DEC_CUENSALDO, M.VCH_MONEDESCRIPCION INTO P_SAL, P_MONEDA
	FROM EUREKA.CUENTA C
	INNER JOIN EUREKA.MONEDA M
	ON C.CHR_MONECODIGO = M.CHR_MONECODIGO
	WHERE CHR_CUENCODIGO = P_NUCUENTA;
END;



BEGIN
	EUREKA.PR_CUENTA_MONEDA ('00100001', :p_sal$NUMBER, :p_moneda$VARCHAR2);
END;