-- T2: Desarrollar un procedimiento que retorne de una cuenta
--     su saldo y el nombre de la moneda. EUREKA

CREATE OR REPLACE PROCEDURE EUREKA.PR_SAL_MON
( CTA IN VARCHAR2, SALDO OUT NUMBER, MDA OUT VARCHAR2)
AS
BEGIN
	SELECT C.DEC_CUENSALDO, MONEDA.VCH_MONEDESCRIPCION INTO SALDO, MDA 
	FROM EUREKA.CUENTA C INNER JOIN EUREKA.MONEDA
	ON C.CHR_MONECODIGO= MONEDA.CHR_MONECODIGO 
	WHERE C.CHR_CUENCODIGO=CTA;
END;



BEGIN
	EUREKA.PR_SAL_MON ('00100002', :saldo$NUMBER, :mda$VARCHAR2);
END;