/*TAREA 3
CREAR 2 ENLACES A BASES DE DATOS DE SUS COMPAÑEROS

HACER UN PROCEDIMIENTO QUE CONSULTE LA TABLA SCOTT DE SU BASE DE DATOS Y LA DE SUS COMPAÑEROS EN UN SOLO CURSOR
*/

CREATE PUBLIC DATABASE LINK DB_TALAVERA
CONNECT TO system identified BY oracle
USING '172.17.3.42:1521/orcl';

CREATE PUBLIC DATABASE LINK DB_MICHAEL
CONNECT TO system identified BY oracle
USING '172.17.3.60:1521/orcl';

CREATE OR REPLACE PROCEDURE SCOTT.CONSULTAR_TABLAS
(
	P_NOMBRE IN EMP.ENAME%TYPE,
	P_CURSOR OUT NOCOPY SYS_REFCURSOR
)
AS	
	V_CRITERIO VARCHAR2(100);
BEGIN
  		V_CRITERIO := '%' || P_NOMBRE || '%';
  		OPEN P_CURSOR FOR
			SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
			FROM SCOTT.EMP@DB_TALAVERA
			WHERE ENAME LIKE V_CRITERIO
			UNION
			SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO 
			FROM SCOTT.EMP@DB_MICHAEL
			WHERE ENAME LIKE V_CRITERIO
			UNION 
			SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO 
			FROM SCOTT.EMP
			WHERE ENAME LIKE V_CRITERIO;
END;
/

BEGIN
	SCOTT.CONSULTAR_TABLAS ('AL', :p_cursor$REFCURSOR);
END;



DECLARE 
	V_CURSOR SYS_REFCURSOR;
	V_REC_EMP SCOTT.EMP%ROWTYPE;
BEGIN
	SCOTT.CONSULTAR_TABLAS('GU', V_CURSOR);
	LOOP
		FETCH V_CURSOR INTO V_REC_EMP;
		EXIT WHEN V_CURSOR%NOTFOUND;
			DBMS_OUTPUT.PUT_LINE(V_REC_EMP.EMPNO || ' - ' || V_REC_EMP.ENAME );
	END LOOP;
	CLOSE V_CURSOR;
END;