
CREATE PUBLIC DATABASE LINK DB_NADIA
CONNECT TO system IDENTIFIED BY oracle
USING 'NADIA';


SELECT * FROM scott.emp@db_nadia;


CREATE PUBLIC DATABASE LINK DB_MICHAEL
CONNECT TO system IDENTIFIED BY oracle
USING '172.17.3.60:1521/ORCL';

select * from scott.emp@DB_MICHAEL;



CREATE PUBLIC DATABASE LINK DB_TALAVERA
CONNECT TO system IDENTIFIED BY oracle
USING '(DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 172.17.3.42)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = ORCL)
    )
  )';

select * from scott.emp@db_talavera;


